version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - ./test:/app/test
      - ./db:/app/db
    environment:
      DATABASE_CONNECTION: "${DATABASE_CONNECTION}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      RAILS_ENV: "${RAILS_ENV}"
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
