default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_CONNECTION'] { 'localhost' } %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default 

test:
  <<: *default

production:
  <<: *default
  port: 25060