default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_CONNECTION'] { 'db' } %>
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default 
  database: boilerplate_dev

test:
  <<: *default
  database: boilerplate_test

production:
  <<: *default
  database: boilerplate_prod

